### ISSUE TITLE
Custom syscalls crash CX 4.4

### ISSUE THREAD

**Issue by duvallj** [lkjcalc/nTxt#2]
Running the latest release of nTxt, on a TI-nSpire CX hardware model V, ndless + OS 4.4.0.532, copy or pasting any text crashes the calculator. I believe this is due to the syscall addresses being wrong somehow.

**Comment by lkjcalc** [comment]
I can't reproduce the issue. Are you sure you have the most recent release of nTxt? (from https://github.com/lkjcalc/nTxt/releases)

**Comment by duvallj** [comment]
Wow I was completely wrong. I was using an old version by accident. Sorry for my tardiness!
