### ISSUE TITLE
Crash on 4.4

### ISSUE THREAD

**Issue by farefernandez** [lkjcalc/nTxt#3]
Hi!

When I run ntxt on my Ti-nspire cx cas (OS 4.4) a pop up opens saying "Ndless: Activating compatibility mode. This application hasn't been updated to work with your hardware. You may run into weird issues!"

It might be related to #2 

I'm running the latest os 4.4 and nTxt 2.7 freshly downloaded.

Thanks!!

**Comment by lkjcalc** [comment]
That pop up is normal. Does it work after that or does it crash?

**Comment by lkjcalc** [comment]
This should probably be fixed now, I rewrote the graphics part to use the new Ndless lcd_blit API.
