### ISSUE TITLE
Fuzzy Chars on ti-classic

### ISSUE THREAD

**Issue by wnke** [lkjcalc/nTxt#4]
The characters are all fuzzy and unreadable:

![p_20170623_154242](https://user-images.githubusercontent.com/8290028/27487142-c2e6e802-582a-11e7-9542-fc2d757bf7b6.jpg)
 
I'm using ndless 3.9 and nTxt 27.
This does not happen when I use nTxt 06 nor nTxt 17.

**Comment by lkjcalc** [comment]
That's probably because Ndless made some non-backward compatible changes to the way the screen is handled.
I rewrote the code to use the new API. I couldn't test it on real hardware though.
Can you check if the attached build fixes the problem on your calculator?

[nTxt.tns.zip](https://github.com/lkjcalc/nTxt/files/2047972/nTxt.tns.zip)

**Comment by Hairo** [comment]
Still have the same issue, if it's of any help the last build that worked is from 10/10/14.

**Comment by lkjcalc** [comment]
Ok, what calculator model and OS do you have, and have you installed the newest ndless release?

**Comment by Hairo** [comment]
I'm using a clickpad CAS with 3.9 ndless (the lastest version available for non-CX models).

**Comment by lkjcalc** [comment]
So the ndless you installed is the newest, installer "ndless_installer_3.9.0_classic_new.tns" from [https://github.com/ndless-nspire/Ndless/releases/tag/v4.5](url) ?

**Comment by Hairo** [comment]
Yes, i installed it from there, from the 4.5 zip.

**Comment by lkjcalc** [comment]
Hm well that's annoying. I don't see an obvious mistake in the nTxt code nor in the Ndless code. Guess I'll have to find my calculator and debug...

In the meantime, maybe the following binary works as a workaround?
[nTxt.tns.zip](https://github.com/lkjcalc/nTxt/files/2058001/nTxt.tns.zip)

**Comment by Hairo** [comment]
Now it looks like this
![dsc_1283](https://user-images.githubusercontent.com/7422368/40791837-6bd0ab9e-64c6-11e8-806e-1f765a83494f.JPG)

**Comment by lkjcalc** [comment]
Ah yes, I see my mistake now. But I think this one should be correct:
[nTxt.tns.zip](https://github.com/lkjcalc/nTxt/files/2064501/nTxt.tns.zip)

**Comment by Hairo** [comment]
It's working fine now, thanks and sorry for all the trouble.

**Comment by lkjcalc** [comment]
Thank _you_ for helping me figure out the problem.

I also found an unrelated old bug while testing. The new nTxt29 fixes both problems.
